# Generated by Django 4.1.1 on 2022-09-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='static/img/', verbose_name='.jpg')),
                ('author', models.CharField(max_length=25, verbose_name='Автор')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
